[profile.default]
version = "1.0.0"
src = "src"
out = "out"
libs = ["dependencies", ".venv/lib/python3.13/site-packages"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 10000
verbosity = 3
wrap_comments = true
gas_reports = ["send_and_receive_editions", "ERC1155TL"]
show_progess = true

[fuzz]
runs = 1024

[vyper]
path="./vyper.sh"

[dependencies]
forge-std = "1.9.7"
tl-creator-contracts = "3.3.1"

[soldeer]
recursive_deps = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARB_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
shape_sepolia = "${SHAPE_SEPOLIA_RPC_URL}"
mainnet = "${ETH_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"
base = "${BASE_RPC_URL}"
shape = "${SHAPE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
arbitrum_sepolia = {  key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
base_sepolia = {  key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.basescan.org/api" }
mainnet = { key = "${ETHERSCAN_KEY}"}
arbitrum = { key = "${ETHERSCAN_KEY}", url = "https://api.arbiscan.io/api" }
base = { key = "${ETHERSCAN_KEY}", url = "https://api.basescan.org/api" }