[profile.default]
src = "src"
out = "out"
libs = ["dependencies", ".venv/lib/python3.13/site-packages"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 10000
verbosity = 3
wrap_comments = true
gas_reports = ["send_and_receive_editions", "ERC1155TL"]
show_progess = true

[fuzz]
runs = 1024

[vyper]
path="./vyper.sh"

[dependencies]
forge-std = "1.9.7"
tl-creator-contracts = "3.3.1"

[soldeer]
recursive_deps = true
