[project]
name = "tl-send-and-redeem"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "snekmate==0.1.1",
    "vyper==0.4.1",
]
